### ISSUE TITLE
if n_channels: 1 then RuntimeError

### ISSUE THREAD

**Issue by wolfryu** [hysts/pytorch_image_classification#14]
Thank you for your excellent work and share !!!
I have own dataset with channel 1,  64X64 gray scale images.
For all network(vgg16, resnet18 ...), if I set n_channels: 1 in yaml file, following error shows:

Traceback (most recent call last):
  File "train.py", line 436, in <module>
    main()
  File "train.py", line 404, in main
    validate(0, config, model, val_loss, val_loader, logger,
  File "train.py", line 259, in validate
    outputs = model(data)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/apex/amp/_initialize.py", line 196, in new_fwd
    output = old_fwd(*applier(args, input_caster),
  File "/media/zzks/xi/2020PJ/lab/pytorch_image_classification/pytorch_image_classification/models/imagenet/vgg.py", line 80, in forward
    x = self._forward_conv(x)
  File "/media/zzks/xi/2020PJ/lab/pytorch_image_classification/pytorch_image_classification/models/imagenet/vgg.py", line 72, in _forward_conv
    x = self.stage1(x)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/zzks/anaconda3/envs/dbnet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 341, in conv2d_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size 64 1 3 3, expected input[100, 3, 64, 64] to have 1 channels, but got 3 channels instead

**Comment by hysts** [comment]
Hi, @wolfryu 

I think applying the following patch should work.
I named the dataset `YourGrayscaleDataset` and put mean and std values of MNIST as placeholder values, so you need to change them.

```diff
--- a/pytorch_image_classification/datasets/datasets.py
+++ b/pytorch_image_classification/datasets/datasets.py
@@ -2,6 +2,7 @@ from typing import Tuple, Union
 
 import pathlib
 
+import PIL.Image
 import torch
 import torchvision
 import yacs.config
@@ -11,6 +12,12 @@ from torch.utils.data import Dataset
 from pytorch_image_classification import create_transform
 
 
+def pil_grayscale_loader(path):
+    with open(path, 'rb') as f:
+        image = PIL.Image.open(f)
+        return image.copy()
+
+
 class SubsetDataset(Dataset):
     def __init__(self, subset_dataset, transform=None):
         self.subset_dataset = subset_dataset
@@ -83,5 +90,18 @@ def create_dataset(config: yacs.config.CfgNode,
         val_dataset = torchvision.datasets.ImageFolder(dataset_dir / 'val',
                                                        transform=val_transform)
         return train_dataset, val_dataset
+    elif config.dataset.name == 'YourGrayscaleDataset':
+        dataset_dir = pathlib.Path(config.dataset.dataset_dir).expanduser()
+        train_transform = create_transform(config, is_train=True)
+        val_transform = create_transform(config, is_train=False)
+        train_dataset = torchvision.datasets.ImageFolder(
+            dataset_dir / 'train',
+            transform=train_transform,
+            loader=pil_grayscale_loader)
+        val_dataset = torchvision.datasets.ImageFolder(
+            dataset_dir / 'val',
+            transform=val_transform,
+            loader=pil_grayscale_loader)
+        return train_dataset, val_dataset
     else:
         raise ValueError()

--- a/pytorch_image_classification/transforms/__init__.py
+++ b/pytorch_image_classification/transforms/__init__.py
@@ -42,6 +42,9 @@ def _get_dataset_stats(
         # RGB
         mean = [0.485, 0.456, 0.406]
         std = [0.229, 0.224, 0.225]
+    elif name == 'YourGrayscaleDataset':
+        mean = np.array([0.1307])  # Mean value of training images
+        std = np.array([0.3081])  # standard deviation of training images
     else:
         raise ValueError()
     return mean, std
```

**Comment by wolfryu** [comment]
thank you so much !!!
