### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Charlotte1891** [hysts/pytorch_image_classification#15]
Hi,

I was trying to run the code from terminal directly using 
```
pip install -r requirements.txt
python train.py --config configs/cifar/resnet.yaml
```
However, I kept getting this assertion error:
```
AssertionError: Key env_info.cuda_version with value <class 'NoneType'> is not a valid type; 
valid types: {<class 'bool'>, <class 'float'>, <class 'tuple'>, <class 'int'>, <class 'list'>, <class 'str'>}
```
Below is the traceback message:
```
Traceback (most recent call last):
  File "train.py", line 436, in <module>
    main()
  File "train.py", line 340, in main
    save_config(get_env_info(config), output_dir / 'env.yaml')
  File "/Users/charlotte/Desktop/classification/pytorch_image_classification/utils/env_info.py", line 19, in get_env_info
    return ConfigNode({'env_info': info})
  File "/Users/charlotte/Desktop/classification/pytorch_image_classification/config/config_node.py", line 6, in __init__
    super().__init__(init_dict, key_list, new_allowed)
  File "/Users/charlotte/opt/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 86, in __init__
    init_dict = self._create_config_tree_from_dict(init_dict, key_list)
  File "/Users/charlotte/opt/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 126, in _create_config_tree_from_dict
    dic[k] = cls(v, key_list=key_list + [k])
  File "/Users/charlotte/Desktop/classification/pytorch_image_classification/config/config_node.py", line 6, in __init__
    super().__init__(init_dict, key_list, new_allowed)
  File "/Users/charlotte/opt/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 86, in __init__
    init_dict = self._create_config_tree_from_dict(init_dict, key_list)
  File "/Users/charlotte/opt/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 132, in _create_config_tree_from_dict
    ".".join(key_list + [str(k)]), type(v), _VALID_TYPES
  File "/Users/charlotte/opt/miniconda3/lib/python3.7/site-packages/yacs/config.py", line 525, in _assert_with_logging
    assert cond, msg
```
Can you please give me some hints about how to fix this? Thanks!

**Comment by hysts** [comment]
Hi, @Charlotte1891 

Sorry, it was a bug that occurred on a machine without GPUs, and I fixed it.

**Comment by Charlotte1891** [comment]
Hi, @hysts 

Thanks for helping;) It works now.
