### ISSUE TITLE
can I run the script without GPU&apex?

### ISSUE THREAD

**Issue by Dee-Why** [hysts/pytorch_image_classification#29]
I'm on my ubuntu server(without GPU), trying to run your script. 
pip install -r requirements.txt   is successful (i ignored the apex requirement, don't have gpu now)
but when I runned the following command, I meet the following issue
and all other .yaml throwed me the same issue.

> ~/code/pytorch_image_classification# python train.py --config configs/cifar/resnet.yaml
Traceback (most recent call last):
  File "train.py", line 449, in <module>
    main()
  File "train.py", line 353, in main
    save_config(get_env_info(config), output_dir / 'env.yaml')
  File "/root/code/pytorch_image_classification/pytorch_image_classification/utils/env_info.py", line 19, in get_env_info
    return ConfigNode({'env_info': info})
  File "/root/code/pytorch_image_classification/pytorch_image_classification/config/config_node.py", line 6, in __init__
    super().__init__(init_dict, key_list, new_allowed)
  File "/root/archiconda3/envs/python38/lib/python3.8/site-packages/yacs/config.py", line 86, in __init__
    init_dict = self._create_config_tree_from_dict(init_dict, key_list)
  File "/root/archiconda3/envs/python38/lib/python3.8/site-packages/yacs/config.py", line 126, in _create_config_tree_from_dict
    dic[k] = cls(v, key_list=key_list + [k])
  File "/root/code/pytorch_image_classification/pytorch_image_classification/config/config_node.py", line 6, in __init__
    super().__init__(init_dict, key_list, new_allowed)
  File "/root/archiconda3/envs/python38/lib/python3.8/site-packages/yacs/config.py", line 86, in __init__
    init_dict = self._create_config_tree_from_dict(init_dict, key_list)
  File "/root/archiconda3/envs/python38/lib/python3.8/site-packages/yacs/config.py", line 129, in _create_config_tree_from_dict
    _assert_with_logging(
  File "/root/archiconda3/envs/python38/lib/python3.8/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Key env_info.pytorch_version with value <class 'torch.torch_version.TorchVersion'> is not a valid type; valid types: {<class 'NoneType'>, <class 'list'>, <class 'bool'>, <class 'int'>, <class 'tuple'>, <class 'float'>, <class 'str'>}

**Comment by hysts** [comment]
Hi, @Dee-Why 

Thank you for reporting this. I fixed it.
